### ISSUE TITLE
AWS EC2: Update Image to Ubuntu 20.04

### ISSUE THREAD

**Issue by dirien** [inlets/inletsctl#108]
The VM image/os should be update to 20.04 due to this >#95 

Mainly its the line 

https://github.com/inlets/inletsctl/blob/ed0bcc767eb9357bef75062dee746684b97eb0bf/cmd/create.go#L489

And should be tested too.

**Comment by cpanato** [comment]
I will update and test it

**Comment by dirien** [comment]
Done thanks @cpanato ! ❤️
