### ISSUE TITLE
Align plan handling inletsctl with inlets-operator

### ISSUE THREAD

**Issue by dirien** [inlets/inletsctl#111]
Comment from the PR of #109 

>That's why I missed this. I'll merge this, but would you like to work on the proposed behaviour change? That's how the operator works ATM:
>
>https://github.com/inlets/inlets-operator/blob/master/controller.go#L553-L569

So this issue is to align the plan handling of inletsctl with inlets-operator

**Comment by dirien** [comment]
done

**Comment by alexellis** [comment]
Thank you
