### ISSUE TITLE
Update inletsctl to use the newest version of inlets PRO by default

### ISSUE THREAD

**Issue by Shikachuu** [inlets/inletsctl#114]
Inletsctl currently uses `0.8.8` az the default version fro inlets PRO, it should be updated to `0.9.1`

## Expected Behaviour
`inletsctl create` should use the latest verison of inlets PRO without specifying it with the `--inlets-pro-version` flag.

## Current Behaviour
It uses `0.8.8`.

## Possible Solution
Update the `inletsProDefaultVersion` const in the create command.

## Context
Users should get the status command on their new tunnel servers.

**Comment by alexellis** [comment]
Approved, thank you.
