### ISSUE TITLE
[Feature] inletsctl should be able to install inlets or inlets-pro

### ISSUE THREAD

**Issue by alexellis** [inlets/inletsctl#12]
inletsctl should be able to install inlets or inlets-pro

## Expected Behaviour

Using the approach to fetch `kubeseal` in faas-cli, inletsctl should be able to grab inlets and inlets-pro in order to run the client in commands like `create` and `kfwd`

## Current Behaviour

Done manually as per https://github.com/inlets/inlets/blob/master/docs/kubernetes.md#try-inlets-with-kind-kubernetes-in-docker

## Possible Solution

Copy solution from faas-cli

https://github.com/openfaas/faas-cli/pull/730

**Comment by alexellis** [comment]
@Waterdrips do you want to take this one?

**Comment by alexellis** [comment]
Different maintainers for inlets, but happy for you to take this

**Comment by alexellis** [comment]
Do you have any questions on this @Waterdrips? Do you think you can get a PR up this week?

**Comment by Waterdrips** [comment]
Ill get this done tomorrow.
