### ISSUE TITLE
Cannot install inletsctl from inletsctl.inlets.dev

### ISSUE THREAD

**Issue by starbops** [inlets/inletsctl#124]
## Expected Behaviour

Can install `inletsctl` from `inletsctl.inlets.dev`.

## Current Behaviour

The domain `inletsctl.inlets.dev` cannot be resolved so the command to install `inletsctl` does not work.

<img width="546" alt="image" src="https://user-images.githubusercontent.com/1827717/221616862-28f6e201-c539-435a-ae7b-91bc26c8dd26.png">

## Possible Solution

Either fix the domain setting or use an alternative way to install `inletsctl`:

```
arkade get inlets-pro inletsctl
```

## Steps to Reproduce (for bugs)

1. `curl -sLSf https://inletsctl.inlets.dev | sudo sh`

## Context

Users cannot install inletsctl following the steps on the README.

## Your Environment

* inlets Pro version `inlets-pro version` 

* inletsctl version `inletsctl version` 

* Cloud provider and region being used

* Operating System and version (e.g. Linux, Windows, MacOS): `uname -a`

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
Thanks for flagging this.

I think it got wiped out when I moved the website to GitHub Actions after Netlify's build servers were down.

The new record for inletsctl.inlets.dev should show up again soon.

**Comment by starbops** [comment]
The domain is back now. Thanks for the quick fix!
