### ISSUE TITLE
Update exit server configuration

### ISSUE THREAD

**Issue by doowb** [inlets/inletsctl#131]
I'd like to be able to add additional domains to an existing exit server without having to create a new one. I looked through the docs and issues and I haven't found information on either of the following:

  1. Is this possible through `inletsctl`?
  2. If I ssh into the exit server, what needs to be updated to add more domains to the `inlets server` command?

## Expected Behaviour

Ability to update an existing exit server:

```sh
inletsctl update \
  --provider digitalocean \
  --id 1235678 \
  --access-token-file $HOME/access-token \
  --letsencrypt-domain existing.example.com \
  --letsencrypt-domain new.example.com \
  --letsencrypt-email webmaster@example.com
```

In the example, I'm showing that the flags used to create the server would still need to be provided. This allows for removing domains if necessary.

## Current Behaviour

Currently, `inletsctl update` only prints instructions on how to update `inletsctl`. If this also provided instructions on how to update the server, that could be useful.

## Possible Solution

I'm assuming that updating is not as straightforward as creating, since creating makes use of a cloud config and updating would require access to ssh into the machine, which may be different for each cloud provider. Therefore, one possible solution is printing provider specific docs when `inletsctl update --provider digitalocean --id 1235678` is used.

## Context

I'd like to expose additional services through the same tunnel without having to recreate the exit server. When I recreate the exit server, I get a new IP address, which needs to be updated in my DNS records. I could buy a static IP address to attach to the exit servers, but that still requires additional steps to manage detaching, then attaching it to the new server.

## Your Environment

* inlets Pro version `inlets-pro version` 
```
Version: 0.9.32 - 4a9a113658ac9ae1f6dcc430b76414d520d656fe
```

* inletsctl version `inletsctl version` 
```
Version: 0.8.29
Git Commit: f98ff8481f36d16ea2d76194a3500d282d37e973
Build target: darwin/arm64
```

* Cloud provider and region being used

- digitalocean
- nyc1

* Operating System and version (e.g. Linux, Windows, MacOS): `uname -a`

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
Hi @doowb 

Thanks for taking time to write this up.

We have started to expand on the inlets server's API a little with the `status` command and metrics, however we haven't considered re-writing the configuration for the token, list of domains etc and I think you've landed on the two things we'd suggest:

1 - delete and re-create the VM as required
2 - log in via SSH and tweak

For folks who think they'll need to do 1 or 2 often, we have "manual setup" instructions like here: [Expose Kubernetes services via inlets tunnels on AWS EC2](https://inlets.dev/blog/2024/06/06/tunnel-k8s-via-aws-ec2.html), which means you definitely have an SSH key pre-installed.

For now, I would suggest logging into the machine via SSH and editing: `/etc/defaults/inlets-pro` file then restart the server.

One other thing that might be of interest is our [exploration of hosted tunnels](https://inlets.dev/blog/2024/06/18/magic-kubernetes-ingress.html). With this solution, we'd be hosting the tunnel server, and you'd have a way to reconfigure the various domains you needed via a CLI or UI.

Let me know if you'd like to try out the Kubernetes Ingress Tunnels. Whilst we haven't mentioned it on the blog post, they also work with Caddy/Nginx running directly on a host.

Alex

**Comment by alexellis** [comment]
One more thing I should mention..

If you have an ever-changing list of domains, you might be better exposing ports 80 and 443 over TCP, then running an ingress controller locally. That way you just edit your local config file and it's immediately applied.

With a local HTTP01 challenge:

https://docs.inlets.dev/tutorial/caddy-http-tunnel/#setup-caddy-2x

With a wildcard domain:

https://inlets.dev/blog/2023/01/17/expose-multiple-services-with-inlets-and-caddy.html

**Comment by doowb** [comment]
> For now, I would suggest logging into the machine via SSH and editing: `/etc/defaults/inlets-pro` file then restart the server.

Thank you! This will work for my use case right now, however, I'll probably look into adding caddy and using a wildcard domain soon. From that post, it looks like adding too many domains or changing them too often, directly in the inlets config, may run into letsencrypt rate limits. I had some issues getting traefik to work using the DNS challenge, but I didn't try caddy yet.

> One other thing that might be of interest is our [exploration of hosted tunnels](https://inlets.dev/blog/2024/06/18/magic-kubernetes-ingress.html).

This post is what reminded me to come here and look for a way to update the domains :) The post implied that my services had to be running in kubernetes (or similar), but it's nice to know that I could use another reverse proxy. In that case, would there just be a specific inlets command that's used for the client instead of the k8s deployment? Right now, I'm running the inlets client through docker compose with upstreams on the host machine.

I consider this issue closed, unless you think this contains any information that may be used to update inletsctl once the inlets server api has been expanded.

**Comment by alexellis** [comment]
We'll close it, but keep it unlocked so other people can chat here or we can post future ideas later on. @welteki is the one who came up with the Caddy + wildcard idea.

Yes, if you had an exccessive amount of domains with the --letsencrypt-domain flags, then you'd perhaps run into rate limits as they use a HTTP01 challenge - so one cert per domain. DNS01 (with a wildcard) uses a * pattern that means you can put whatever you want on the left hand side of the domain using a single cert.

DNS01 is harder to set up because you need a credential, but Han's example is a good start if your domain is on Cloudflare, otherwise you can host your domain's nameservers on DO for free and use a token from them.

**Comment by alexellis** [comment]
To try out the hosted tunnel, send me your list of DNS sub-domains via email and I'll set it up for you today.
