### ISSUE TITLE
Add provisioner for AWS EC2

### ISSUE THREAD

**Issue by alexellis** [inlets/inletsctl#15]
Add provisioner for AWS EC2

Provision interface:

https://github.com/inlets/inletsctl/blob/master/pkg/provision/provision.go

DigitalOcean:

https://github.com/inlets/inletsctl/blob/master/pkg/provision/digitalocean.go

Create with Ubuntu 18.04 or 16.04 using the cheapest instance that has a Public IP. Default region to Europe, but should be configurable.

**Comment by adam7** [comment]
Isn't this closed by #16 ?

**Comment by alexellis** [comment]
@adamjohnson01 did we get the auto-closing keywords right in the PR?

Can this be closed now?

**Comment by adamjohnson01** [comment]
@alexellis , I do not think that I got the auto closing stuff correct, this can be closed.
