### ISSUE TITLE
Compress each binary release

### ISSUE THREAD

**Issue by alexellis** [inlets/inletsctl#30]
We should compress each binary so that the download is quicker. Tar/gzip seems the most portable option.

The get.sh script must also be updated. 

This is needed after adding the EC2 SDK which took us from 8mb to 38mb 🤯

**Comment by alexellis** [comment]
@utsavanand2 one for you sir?

**Comment by utsavanand2** [comment]
<img width="725" alt="Screenshot 2020-01-21 at 8 16 41 PM" src="https://user-images.githubusercontent.com/25264581/72826929-cde49e00-3c9f-11ea-82fc-9e214a44f402.png">

For the sake of documentation, I am posting the size comparison of gzip and bzip2 compression of the inletsctl binary for linux

**Comment by alexellis** [comment]
@utsavanand2 how soon can you get a PR up for this? You'll need to edit the bash scripts, maybe the makefile and the travis file.

**Comment by alexellis** [comment]
get.sh also will need an update to download and extract.

**Comment by utsavanand2** [comment]
I'll put this one up as soon as I can. Most likely tonight only!

**Comment by utsavanand2** [comment]
I've updated get.sh but need to update the Makefile and travis.yml
