### ISSUE TITLE
[Feature] Look for an INLETS_ACCESS_TOKEN_FILE env var if --access-token-file is not set

### ISSUE THREAD

**Issue by Waterdrips** [inlets/inletsctl#34]
It would be nice to be able to set a env variable for the location of the access-token file. At the moment we need to set it for every command, and its lots to type

## Expected Behaviour

if you ommit --access-token-file and there is an environment variable set (`INLETS_ACCESS_TOKEN_FILE`) then we could try to use the value in that file (if it exists)

## Current Behaviour

you have to set it every time

## Possible Solution

check if the flag is set, if so we use the flag vlaue, if its not we could see if the env variable is set, and if it is we could use the value.

**Comment by alexellis** [comment]
Please feel free to work on this, the flag should override the ENV var
