### ISSUE TITLE
Default --remote-tcp to localhost

### ISSUE THREAD

**Issue by Waterdrips** [inlets/inletsctl#35]
We can set localhost as the default for the `--remote-tcp` flag. This would allow inlets-pro users who are forwarding traffic to the same host that is running the inlets-pro client.

## Expected Behaviour

if the flag `--remote-tcp` is not set we could default to `localhost` which would forward traffic to the host running the inlets-pro client command

## Current Behaviour

you have to set it every time even if you want localhost

## Possible Solution

If we do this, we need to think about how we enable the inlets-pro server initialisation rather than standard inlets, at the moment it checks if `--remote-tcp` is set. 
possibly a `--pro` flag? which could be used if you want localhost, but if you set a `--remote tcp` and didnt use `--pro` it should still enable pro

**Comment by alexellis** [comment]
Sounds good
