### ISSUE TITLE
The delete command does not work for GCE

### ISSUE THREAD

**Issue by utsavanand2** [inlets/inletsctl#39]
The delete command printed out after creating an exit node on GCE does not delete the instance until a `--project-id` flag is provided

## Expected Behaviour

Unless until specified explicitly, the `project-id` should be inferred from the GCE exit node *customID*

## Current Behaviour

<img width="1089" alt="Screenshot 2020-01-30 at 3 34 41 PM" src="https://user-images.githubusercontent.com/25264581/73440095-b29c2180-4376-11ea-8476-244b656bc785.png">

## Possible Solution

Pull Request for the fix: #40 

## Steps to Reproduce (for bugs)

1. create an instance with `gce` as the provider.
2. make note of the printed delete command after successful execution of the above step
3. try deleting the instance with an extra flag for the `--access-token-file`
4. The command would fail with an error: 
    `got HTTP response code 404 with body: Not Found`

## Your Environment

* inletsctl version
Version: 0.4.1
Git Commit: 3f1c896a5ac31d0ee7651a8074fc687e7f0c27ff 

* Operating System and version (e.g. Linux, Windows, MacOS):
MacOS

**Comment by adamjohnson01** [comment]
I think you can close #31 as this is a duplicate of that.
