### ISSUE TITLE
Fix issue with the opening of TCP ports for inlets-pro on GCE

### ISSUE THREAD

**Issue by utsavanand2** [inlets/inletsctl#44]
## Expected Behaviour

The GCE operator should open up ports for inlets-pro
For users switching between inlets OSS and inlets-pro, the firewall rules should be 
updated automatically.

## Current Behaviour

If a firewall rule named inlets for inlets OSS already exists, it doesn't open up ports for inlets-pro

## Possible Solution

PR #45 

## Steps to Reproduce (for bugs)

1. Run inletsctl with inlets OSS
2. Run inletsctl again with inlets-pro

**Comment by alexellis** [comment]
To be fair this isn't going to work. We need all ports to be opened. cc @adamjohnson01 

The point of inlets-pro is that it's a pass-through TCP proxy, so we'd want ports as low as 22, 80 and 443 if that's what the user was punching out.

**Comment by utsavanand2** [comment]
My PR will be opening 22, 80, 443, and ports from 1024 to 65535

**Comment by utsavanand2** [comment]
@alexellis Do you want any other ports to be opened apart from these?

**Comment by utsavanand2** [comment]
Update: The linked PR #45 will open up all TCP traffic
