### ISSUE TITLE
region shown as "" in create command

### ISSUE THREAD

**Issue by alexellis** [inlets/inletsctl#47]
region shown as "" in create command

## Expected Behaviour

```
Requesting host: vibrant-jennings5 in lon1, from digitalocean
```

## Current Behaviour

```
Requesting host: vibrant-jennings5 in , from digitalocean
```

## Steps to Reproduce (for bugs)

1. `./inletsctl create --provider digitalocean --access-token-file  ~/inlets-token`

## Context

Found in master

Problematic area is around the flag parsing and defaults -> https://github.com/inlets/inletsctl/blob/master/cmd/create.go#L96

**Comment by utsavanand2** [comment]
Derek close
