### ISSUE TITLE
Openstack (STACKIT) Support

### ISSUE THREAD

**Issue by dirien** [inlets/inletsctl#79]
## Openstack (STACKIT) Support

inlets is really a cool project, and we (here at the Schwarz Group) would like to use on our own cloud provider STACKIT (https://stackit.de/en/). Openstack is the engine of STACKIT.  

On addition, Kubernetes is a big building block for the future and and i think inlets will help the developers in many area of their work.

To use inlets, it would be sweet to support Openstack/STACKIT too.

I created the provider already, and i just wait to get your approval before I create a pull request for it.

I would be more than happy to get an approval from you.

Looking forward.

**Comment by alexellis** [comment]
(Thanks for the reply, moving this to the inlestctl repo where we talk about and consider adding providers.)

**Comment by alexellis** [comment]
I'm curious whether the code for the inlets provisioner would work with any OpenStack host, or only your internal IT system?

If you're planning on using inlets for commercial work and confidential data, have you also made yourself aware of the differences of inlets OSS and inlets PRO when provisioned by inletsctl/operator? 

I'd suggest reading [inlets tunnel capabilities](https://github.com/inlets/inlets-operator#inlets-tunnel-capabilities)

**Comment by dirien** [comment]
I thought about the same, regarding the code. I for now had the RC file from our opentack installation in mind.

Good thing is that STACKIT is also for the external market. I can give you details maybe in the mail.

Regarding the license: I think only PRO makes sense for us. :)

**Comment by dirien** [comment]
you let me know if you agree with  the  addition of openstack (STACKIT) to inlets?
