### ISSUE TITLE
curl/sudo sh - Install fails on Ubuntu 20.10 

### ISSUE THREAD

**Issue by dashaun** [inlets/inletsctl#88]
SHA comparison failed because the binary got installed in /tmp instead of into /tmp/bin/

## Possible Solution
My workaround was to create /tmp/bin and move the inletsctl from /tmp/ to /tmp/bin/

## Steps to Reproduce (for bugs)

Ubuntu 20.10
1. curl -sLSf https://inletsctl.inlets.dev | sudo sh

## Your Environment

* inletsctl version

```
 _       _      _            _   _ 
(_)_ __ | | ___| |_ ___  ___| |_| |
| | '_ \| |/ _ \ __/ __|/ __| __| |
| | | | | |  __/ |_\__ \ (__| |_| |
|_|_| |_|_|\___|\__|___/\___|\__|_|

Version: 0.8.2
Git Commit: 1ba0bc1ce0e18757422c4de3cb8ca386d0a9d289
```

**Comment by alexellis** [comment]
Hi thank you for updating your version.

I'll take a look into this.

Alex
