### ISSUE TITLE
inlets-pro: command not found

### ISSUE THREAD

**Issue by aniecki** [inlets/inletsctl#93]
This is double strange/error - for the provisioning, don't use the -pro flag, yet the outcome shows to use the pro version, which is not available. 
## Steps to Reproduce (for bugs)

1. curl -sLSf https://inletsctl.inlets.dev | sudo sh
2.

## Your Environment

* inlets version `inlets --version` 
Version: 3.0.1
* Docker/Kubernetes version `docker version` / `kubectl version`:

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
Hi @aniecki 

It seems like you need to buy inlets PRO and have not done so.

Not sure how I can help you here, but I commented on your other issue.

Alex
