### ISSUE TITLE
error="websocket: bad handshake"

### ISSUE THREAD

**Issue by aniecki** [inlets/inletsctl#94]
## Expected Behaviour

Should be able to connect to ec2 server provisioned by inletsctl, even without pro version

## Current Behaviour

ERRO[2021/06/01 11:17:37] Failed to connect to proxy. Response status: 400 - 400 Bad Request. Response body: Client sent an HTTP request to an HTTPS server.  error="websocket: bad handshake"
ERRO[2021/06/01 11:17:37] Remotedialer proxy error                      error="websocket: bad handshake"
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* inlets version `inlets --version` 
Version: 3.0.1
* Docker/Kubernetes version `docker version` / `kubectl version`:

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
Hi @aniecki

inlets OSS is discontinued and was replaced by inlets PRO, you're welcome to check out offers like our 6mo license with 50 USD off. All tooling is for inlets PRO customers only.

https://openfaas.gumroad.com/#VJUPc

Alex
